import '../../goals/models/learning_goal.dart';
import '../../schedule/models/planned_session.dart';
import '../../tasks/models/task.dart';
import '../models/calendar_export_options.dart';

class IcsExportService {
  const IcsExportService();

  String generateIcsForSessions(
    List<PlannedSession> sessions,
    Map<String, Task> taskMap, {
    Map<String, LearningGoal> goalMap = const {},
    String calendarName = 'CogniPlan Schedule',
    DateTime? generatedAt,
  }) {
    final exportTimestamp = (generatedAt ?? DateTime.now()).toUtc();
    final orderedSessions = List<PlannedSession>.from(sessions)
      ..sort((a, b) {
        final startCompare = a.start.compareTo(b.start);
        if (startCompare != 0) {
          return startCompare;
        }
        return a.id.compareTo(b.id);
      });

    final lines = <String>[
      'BEGIN:VCALENDAR',
      'VERSION:2.0',
      'PRODID:-//Cognitive Task Planning System//Calendar Export//EN',
      'CALSCALE:GREGORIAN',
      'METHOD:PUBLISH',
      'X-WR-CALNAME:${_escapeText(calendarName.trim().isEmpty ? 'CogniPlan Schedule' : calendarName.trim())}',
      'X-WR-TIMEZONE:UTC',
    ];

    for (final session in orderedSessions) {
      if (!session.end.isAfter(session.start)) {
        continue;
      }

      final task = taskMap[session.taskId];
      final goal = task?.goalId == null ? null : goalMap[task!.goalId!];
      final title = _cleanTaskTitle(task?.title);

      lines.addAll([
        'BEGIN:VEVENT',
        'UID:${_buildUid(session)}',
        'DTSTAMP:${_formatUtc(exportTimestamp)}',
        'DTSTART:${_formatUtc(session.start.toUtc())}',
        'DTEND:${_formatUtc(session.end.toUtc())}',
        'SUMMARY:${_escapeText(_buildSummary(title))}',
        'DESCRIPTION:${_escapeText(_buildDescription(session, task, goal, title))}',
        'STATUS:${session.isCancelled ? 'CANCELLED' : 'CONFIRMED'}',
        'CATEGORIES:${_buildCategories(task, goal)}',
        'X-COGNIPLAN-SESSION-ID:${_escapeText(session.id)}',
        'X-COGNIPLAN-SESSION-STATUS:${session.status.name.toUpperCase()}',
        if (task != null) 'X-COGNIPLAN-TASK-ID:${_escapeText(task.id)}',
        'END:VEVENT',
      ]);
    }

    lines.add('END:VCALENDAR');
    final content = lines.expand(_foldLine).join('\r\n');
    return '$content\r\n';
  }

  String generateIcsForDateRange({
    required CalendarExportOptions options,
    required List<PlannedSession> sessions,
    required Map<String, Task> taskMap,
    Map<String, LearningGoal> goalMap = const {},
    DateTime? generatedAt,
  }) {
    return generateIcsForSessions(
      sessions,
      taskMap,
      goalMap: goalMap,
      calendarName: options.calendarName,
      generatedAt: generatedAt,
    );
  }

  String _buildUid(PlannedSession session) {
    final normalizedId = session.id
        .replaceAll(RegExp(r'[^A-Za-z0-9._-]'), '_')
        .toLowerCase();
    return 'planned-session-$normalizedId@cogniplan.local';
  }

  String _buildSummary(String title) {
    if (title.toLowerCase().endsWith('focus session')) {
      return title;
    }
    return '$title Focus Session';
  }

  String _buildDescription(
    PlannedSession session,
    Task? task,
    LearningGoal? goal,
    String title,
  ) {
    final lines = <String>[
      'Task: $title',
      'Duration: ${session.plannedDurationMinutes} minutes',
      'Session Status: ${_sessionStatusLabel(session)}',
      if (task != null) 'Task Type: ${task.type.label}',
      if (goal != null) 'Goal: ${goal.title}',
      'Generated by CogniPlan',
    ];

    final taskDescription = task?.description?.trim();
    if (taskDescription != null && taskDescription.isNotEmpty) {
      lines.add('Task Notes: $taskDescription');
    }

    return lines.join('\n');
  }

  String _buildCategories(Task? task, LearningGoal? goal) {
    final categories = <String>{
      'Focus',
      if (task != null) task.type.label,
      if (goal != null) goal.goalType.label,
    };
    return categories.map((value) => value.replaceAll(',', ' ')).join(',');
  }

  String _sessionStatusLabel(PlannedSession session) {
    switch (session.status) {
      case PlannedSessionStatus.pending:
        return 'Pending';
      case PlannedSessionStatus.inProgress:
        return 'In Progress';
      case PlannedSessionStatus.completed:
        return 'Completed';
      case PlannedSessionStatus.missed:
        return 'Missed';
      case PlannedSessionStatus.cancelled:
        return 'Cancelled';
    }
  }

  String _cleanTaskTitle(String? title) {
    final trimmed = title?.trim();
    if (trimmed == null || trimmed.isEmpty) {
      return 'Untitled Session';
    }
    return trimmed;
  }

  String _formatUtc(DateTime value) {
    String twoDigits(int number) => number.toString().padLeft(2, '0');

    return '${value.year.toString().padLeft(4, '0')}'
        '${twoDigits(value.month)}'
        '${twoDigits(value.day)}'
        'T'
        '${twoDigits(value.hour)}'
        '${twoDigits(value.minute)}'
        '${twoDigits(value.second)}'
        'Z';
  }

  String _escapeText(String value) {
    return value
        .replaceAll('\\', r'\\')
        .replaceAll('\r\n', r'\n')
        .replaceAll('\n', r'\n')
        .replaceAll(',', r'\,')
        .replaceAll(';', r'\;');
  }

  List<String> _foldLine(String line) {
    const maxLength = 73;
    if (line.length <= maxLength) {
      return [line];
    }

    final chunks = <String>[];
    var cursor = 0;
    while (cursor < line.length) {
      final end = cursor + maxLength < line.length
          ? cursor + maxLength
          : line.length;
      final chunk = line.substring(cursor, end);
      chunks.add(cursor == 0 ? chunk : ' $chunk');
      cursor = end;
    }
    return chunks;
  }
}
